**welcome to numpy*

In [ ]:
import numpy as np

In [ ]:
myarr = np.array([[3,6,32,7]],np.int8) #to use a int 8 bite (to manage memory) 

In [ ]:
myarr[0,1]

6

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr.dtype

dtype('int8')

In [ ]:
#search numpy types reference

In [ ]:
myarr[0,1] = 56

In [ ]:
myarr[0,1]

56

In [ ]:
myarr

#Array Creation : Conversion from other Python structures

In [ ]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
listarray.dtype

dtype('int32')

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.size

9

In [ ]:
zeros = np.zeros((2,5))

In [ ]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeros.size

10

In [ ]:
zeros.shape

In [ ]:
rng = np.arange(15) #creates a array from 0 to 15

In [ ]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace = np.linspace(1,5,12) #gives 12 elements between 1 and 5 which are equally spaced

In [ ]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
ccc = np.linspace(1,5,5)

In [ ]:
ccc

array([1., 2., 3., 4., 5.])

In [ ]:
emp = np.empty((2,5)) #same as zeros but gives random no.s

In [ ]:
emp

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
emp_like = np.empty_like(ccc)

In [ ]:
emp_like

array([1., 2., 3., 4., 5.])

In [ ]:
ide = np.identity(5)# creates an identiy matrix of 5 x 5

In [ ]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
ide.shape

(5, 5)

In [ ]:
arr = np.arange(99)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr = arr.reshape(3,33) # reshapes the array (see arr not  np )(3x33=99)

In [ ]:
arr 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr = arr.ravel() # makes an one d array of any

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(99,)

In [ ]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
ar = np.array(x)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar.sum(axis = 0) #adds all the rows that is axis 0 

array([12, 15, 18])

In [ ]:
ar.sum(axis = 1) #adds all the colums that is axis 1

array([ 6, 15, 24])

In [ ]:
ar.T # creates the transpose of the matrix (that is the 2D array)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
ar.flat # it kind of makes it flat

In [ ]:
for items in ar.flat:
    print(items)

1
2
3
4
5
6
7
8
9


In [ ]:
# can be done like this too
for items in ar.ravel():
    print(items)

1
2
3
4
5
6
7
8
9


In [ ]:
ar.ndim # no. of dimensions

2

In [ ]:
ar.size

9

In [ ]:
ar.nbytes #total bites consumed

36

In [ ]:
one = np.array([1,34,634,2])

In [ ]:
one.argmax() # This gives the max no.'s index (min) (this is a function other were attribute)

2

In [ ]:
one.argsort() # Here it is in the increasing order (indices)

array([0, 3, 1, 2], dtype=int64)

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar.argmin()

0

In [ ]:
ar.argmax()

8

In [ ]:
ar.argmax(axis=0) # in all the rows the biggest no. is in the index no. 2

array([2, 2, 2], dtype=int64)

In [ ]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
ar2 = np.array([[1, 2, 3],
                [4, 0, 6],
                [3, 1, 2]])

In [ ]:
ar + ar2  # this is bc of numpy only as py cant do it (matrix) 

array([[ 2,  4,  6],
       [ 8,  5, 12],
       [10,  9, 11]])

In [ ]:
[ 2,  4,  6] + [1,2,3] # see the the result
       

[2, 4, 6, 1, 2, 3]

In [ ]:
ar*ar2 #nice

array([[ 1,  4,  9],
       [16,  0, 36],
       [21,  8, 18]])

In [ ]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
ar.sum()

45

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.where(ar>8)# shows the position

(array([2], dtype=int64), array([2], dtype=int64))

In [ ]:
np.nonzero(ar) # tells the positions of non zero no.s

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [ ]:
np.count_nonzero(ar) # counts -_-

9

In [ ]:
import sys

In [ ]:
py_ar = [0,45,55,2]

In [ ]:
np_ar = np.array([0,45,55,2]) # ny_ar = np.array(py_ar)

In [ ]:
sys.getsizeof(1) * len(py_ar)

112

In [ ]:
np_ar.itemsize * np_ar.size # same as above

16

In [ ]:
## see numpy takes only 16  where as python takes 112

In [ ]:
np_ar.tolist() # makes a python list of the array

[0, 45, 55, 2]

In [ ]:
np_ar

array([ 0, 45, 55,  2])